### ISSUE TITLE
PCs can't attack anymore

### ISSUE THREAD

**Issue by paradoja** [SobranDM/foundryvtt-wwn#80]
Summary: When clicking to attack as a PC, the below exception is raised and nothing happens.

Steps:
1. Base world, no modules; version 1.3.0 of the WWN world
2. Create a PC with a weapon (no matter if from a Compendium or manually)
3. Click on the inventory section to try to attack (no matter if there's a token or not in scene)

Expected: To see an attack happening

Actual result: Nothing appears to happen.
In the console the following exception is raised:

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'system')
    at WwnActor.rollAttack (entity.js:477:8)
    at WwnActor.targetAttack (entity.js:459:12)
    at WwnItem.rollWeapon (entity.js:248:16)
    at HTMLDivElement.<anonymous> (actor-sheet.js:150:14)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

**Comment by paradoja** [comment]
Argh, mostly ignore the issue - the skill was missing on PCs on the test, but interestingly, on the first migrated world (with fully developed PCs) something similar was happening. But there are lots of modules added, so it may be something else. Will investigate and create a new issue if necessary, please close this one for now.
